// =====================================================================
//  CS3530 Assignment-1 : Multi-Client Quiz System with LLM Integration
//  Roll number : cs23btech11047
//  File        : protocol.h  (shared by Part A and Part B, server+client)
//
//  Wire format (12-byte fixed header, big-endian / network byte order):
//
//    0       2      3      4              8             12
//    +-------+------+------+--------------+--------------+
//    | magic | vers | flag |     type     |  payload_len |
//    +-------+------+------+--------------+--------------+
//    |                   payload (payload_len bytes, UTF-8 JSON/text)  |
//
//    magic       uint16  0x515A ("QZ")  - resynchronisation / sanity check
//    version     uint8   0x01           - protocol version
//    flags       uint8   bit0 CACHE_HIT, bit1 CACHE_MISS (Part B only)
//    type        uint32  Messagetype enum
//    payload_len uint32  number of payload bytes that follow (0 allowed)
//
//  Python equivalent:  struct.pack('!HBBII', 0x515A, 1, flags, type, len)
// =====================================================================
#pragma once

#include <iostream>
#include <string>
#include <vector>
#include <sstream>
#include <map>
#include <set>
#include <memory>
#include <algorithm>
#include <cctype>
#include <chrono>
#include <cerrno>
#include <atomic>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <cstdlib>
#include <stdexcept>

#include <unistd.h>
#include <signal.h>
#include <sys/socket.h>
#include <sys/time.h>
#include <sys/types.h>
#include <netinet/in.h>
#include <netinet/tcp.h>
#include <arpa/inet.h>
#include <pthread.h>
#include <netdb.h>

#include "json.hpp"

using namespace std;
using json = nlohmann::json;

// ------------------------- framing constants -------------------------
static const uint16_t QUIZ_MAGIC   = 0x515A;      // 'Q','Z'
static const uint8_t  QUIZ_VERSION = 0x01;
static const uint32_t MAX_PAYLOAD  = 1u << 20;    // 1 MiB hard cap

// ------------------------- message types -----------------------------
enum Messagetype : uint32_t {
    GENRE_REQUEST       = 1,   // C -> S  payload: genre string
    QUESTION_DELIVERY   = 2,   // S -> C  payload: JSON question (no answer)
    ANSWER_SUBMISSION   = 3,   // C -> S  payload: "A".."D"
    RESULT_DELIVERY     = 4,   // S -> C  payload: JSON verdict + score
    LEADERBOARD_REQUEST = 5,   // C -> S  payload: empty
    LEADERBOARD_DELIVERY= 6,   // S -> C  payload: JSON leaderboard
    SESSION_END         = 7,   // both    payload: JSON final summary
    KEEP_ALIVE          = 8,   // S -> C  payload: empty
    ALIVE_OK            = 9,   // C -> S  payload: empty
    USERNAME_SUBMISSION = 10,  // C -> S  payload: username string
    ERROR_MSG           = 11,  // S -> C  payload: JSON {"error": "..."}
    SERVER_INFO         = 12   // S -> C  payload: JSON session parameters
};

// ------------------------- header flags ------------------------------
enum MessageFlag : uint8_t {
    FLAG_NONE       = 0x00,
    FLAG_CACHE_HIT  = 0x01,   // question served from the server-side cache
    FLAG_CACHE_MISS = 0x02    // question was freshly generated by the LLM
};

#pragma pack(push, 1)
struct MessageHeader {
    uint16_t magic;
    uint8_t  version;
    uint8_t  flags;
    uint32_t type;            // host order once returned by recvMessage()
    uint32_t payload_length;  // host order once returned by recvMessage()
};
#pragma pack(pop)

static const size_t HEADER_SIZE = 12;

enum RecvStatus {
    RECV_OK      =  1,
    RECV_CLOSED  =  0,   // orderly shutdown by peer
    RECV_TIMEOUT = -1,   // SO_RCVTIMEO expired before any byte arrived
    RECV_ERROR   = -2,
    RECV_BADMSG  = -3    // bad magic / version / oversized payload
};

// ------------------------- quiz payload ------------------------------
struct QuizQuestion {
    string         q;
    vector<string> options;   // "A) ...", "B) ...", "C) ...", "D) ..."
    string         a;         // single letter A-D
};

// ------------------------- small utilities ---------------------------
inline string trimCopy(string s) {
    size_t b = s.find_first_not_of(" \t\r\n");
    if (b == string::npos) return "";
    size_t e = s.find_last_not_of(" \t\r\n");
    return s.substr(b, e - b + 1);
}

inline string upperCopy(string s) {
    transform(s.begin(), s.end(), s.begin(), ::toupper);
    return s;
}

inline string lowerCopy(string s) {
    transform(s.begin(), s.end(), s.begin(), ::tolower);
    return s;
}

// "C", " c ", "C) George Washington" -> 'C'  ;  0 when nothing usable
inline char answerLetter(const string& raw) {
    string s = upperCopy(trimCopy(raw));
    for (size_t i = 0; i < s.size(); ++i) {
        if (s[i] >= 'A' && s[i] <= 'D') {
            // reject a letter that is part of a longer word, e.g. "BERLIN"
            bool next_ok = (i + 1 >= s.size()) || !isalpha((unsigned char)s[i + 1]);
            if (next_ok) return s[i];
        }
    }
    return 0;
}

inline const char* msgName(uint32_t t) {
    switch (t) {
        case GENRE_REQUEST:        return "GENRE_REQUEST";
        case QUESTION_DELIVERY:    return "QUESTION_DELIVERY";
        case ANSWER_SUBMISSION:    return "ANSWER_SUBMISSION";
        case RESULT_DELIVERY:      return "RESULT_DELIVERY";
        case LEADERBOARD_REQUEST:  return "LEADERBOARD_REQUEST";
        case LEADERBOARD_DELIVERY: return "LEADERBOARD_DELIVERY";
        case SESSION_END:          return "SESSION_END";
        case KEEP_ALIVE:           return "KEEP_ALIVE";
        case ALIVE_OK:             return "ALIVE_OK";
        case USERNAME_SUBMISSION:  return "USERNAME_SUBMISSION";
        case ERROR_MSG:            return "ERROR_MSG";
        case SERVER_INFO:          return "SERVER_INFO";
        default:                   return "UNKNOWN";
    }
}

inline double nowSeconds() {
    struct timeval tv;
    gettimeofday(&tv, nullptr);
    return tv.tv_sec + tv.tv_usec / 1e6;
}

inline string timestampString() {
    struct timeval tv;
    gettimeofday(&tv, nullptr);
    time_t secs = tv.tv_sec;
    struct tm tmv;
    localtime_r(&secs, &tmv);
    char buf[32];
    strftime(buf, sizeof(buf), "%H:%M:%S", &tmv);
    char out[48];
    snprintf(out, sizeof(out), "%s.%03d", buf, (int)(tv.tv_usec / 1000));
    return string(out);
}

inline string peerString(int fd) {
    sockaddr_in addr;
    socklen_t len = sizeof(addr);
    if (getpeername(fd, (sockaddr*)&addr, &len) != 0) return "unknown";
    char ip[INET_ADDRSTRLEN] = {0};
    inet_ntop(AF_INET, &addr.sin_addr, ip, sizeof(ip));
    return string(ip) + ":" + to_string(ntohs(addr.sin_port));
}

// ------------------------- transport helpers -------------------------
// Byte counters so the client can report application level throughput.
struct ByteCounters {
    std::atomic<long long> sent;
    std::atomic<long long> received;
    ByteCounters() : sent(0), received(0) {}
};
inline ByteCounters& counters() { static ByteCounters c; return c; }

inline bool sendAll(int fd, const char* buf, size_t len) {
    size_t off = 0;
    while (off < len) {
        ssize_t n = send(fd, buf + off, len - off, MSG_NOSIGNAL);
        if (n > 0) { off += (size_t)n; continue; }
        if (n < 0 && errno == EINTR) continue;
        if (n < 0 && (errno == EAGAIN || errno == EWOULDBLOCK)) { usleep(2000); continue; }
        return false;
    }
    counters().sent += (long long)len;
    return true;
}

// Header and payload are concatenated and written with a single sendAll()
// so a frame is never split by a concurrent writer on the same socket.
inline bool sendMessage(int fd, Messagetype type, const string& payload,
                        uint8_t flags = FLAG_NONE) {
    if (payload.size() > MAX_PAYLOAD) return false;
    MessageHeader h;
    h.magic          = htons(QUIZ_MAGIC);
    h.version        = QUIZ_VERSION;
    h.flags          = flags;
    h.type           = htonl((uint32_t)type);
    h.payload_length = htonl((uint32_t)payload.size());

    string frame;
    frame.reserve(HEADER_SIZE + payload.size());
    frame.append((const char*)&h, HEADER_SIZE);
    frame.append(payload);
    return sendAll(fd, frame.data(), frame.size());
}

inline bool sendJson(int fd, Messagetype type, const json& j,
                     uint8_t flags = FLAG_NONE) {
    return sendMessage(fd, type, j.dump(), flags);
}

// allow_initial_timeout: return RECV_TIMEOUT when SO_RCVTIMEO fires before
// the first byte of a frame. Once a frame has started we keep waiting so a
// message is never truncated.
inline int recvExactly(int fd, char* buf, size_t len, bool allow_initial_timeout) {
    size_t off = 0;
    int    stalls = 0;
    while (off < len) {
        ssize_t n = recv(fd, buf + off, len - off, 0);
        if (n > 0) { off += (size_t)n; continue; }
        if (n == 0) return RECV_CLOSED;
        if (errno == EINTR) continue;
        if (errno == EAGAIN || errno == EWOULDBLOCK) {
            if (off == 0 && allow_initial_timeout) return RECV_TIMEOUT;
            if (++stalls > 6) return RECV_ERROR;   // peer died mid-frame
            continue;
        }
        return RECV_ERROR;
    }
    counters().received += (long long)len;
    return RECV_OK;
}

inline int recvMessage(int fd, MessageHeader& out, string& payload,
                       bool allow_timeout = true) {
    MessageHeader raw;
    int st = recvExactly(fd, (char*)&raw, HEADER_SIZE, allow_timeout);
    if (st != RECV_OK) return st;

    if (ntohs(raw.magic) != QUIZ_MAGIC || raw.version != QUIZ_VERSION)
        return RECV_BADMSG;

    uint32_t len = ntohl(raw.payload_length);
    if (len > MAX_PAYLOAD) return RECV_BADMSG;

    payload.assign(len, '\0');
    if (len > 0) {
        st = recvExactly(fd, &payload[0], len, false);
        if (st != RECV_OK) return st;
    }

    out.magic          = QUIZ_MAGIC;
    out.version        = raw.version;
    out.flags          = raw.flags;
    out.type           = ntohl(raw.type);
    out.payload_length = len;
    return RECV_OK;
}

// ------------------------- server side types -------------------------
struct ClientSession {
    int    socket    = -1;
    int    score     = 0;
    int    answered  = 0;
    string peer;
    double joined_at = 0.0;
};

struct ClientThreadData {
    int clientSocket;
};

void*  handle_client(void* arg);
string getQuiz(const string& genre);
bool   reserveLLM();
